sudo: false
language: "node_js"
node_js:
  - "6"
  - "7"
script:
  - npm install
  - npm run coverage
  - eslint --max-warnings 0 .
after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls
