sudo: false
language: "node_js"
node_js:
  - "6"
  - "7"
before_script:
  - npm install standard
  - standard
script:
  - npm install istanbul
  - istanbul cover ./node_modules/.bin/jasmine --report lcovonly
after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls