sudo: false
language: "node_js"
node_js:
  - "6"
  - "8"
script:
  - git config --global user.email "thought@knappi.org"
  - git config --global user.name "Thought in Travis"
  - npm install
  - npm run coverage
  - eslint --max-warnings 0 .
after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls
